#!/bin/bash -eu

DEPS=(
  build-essential
  bundler
  jekyll
  ruby-full
)

echo "==> Updating package lists..."
sudo apt-get update

echo "==> Installing dependencies..."
sudo apt-get install --no-install-recommends --yes "${DEPS[@]}"

echo "==> Installing gems..."
sudo bundle
