name: Build Builder Images

on:
  push:
    paths:
      - 'docker/builder.dockerfile'
      - '.github/workflows/ci-builder.yml'

jobs:
  build-builders:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ trixie, testing, sid ]
    steps:
      - uses: docker/build-push-action@v7
        with:
          file: docker/builder.dockerfile
          push: false
          tags: turnertech/nmbs-builder:${{ matrix.release }}
          build-args: |
            DEBIAN_RELEASE=${{ matrix.release }}
