name: Build Builder Images

on:
  push:
    paths:
      - 'docker/builder.dockerfile'
      - '.github/workflows/ci-builder.yml'

jobs:
  build-builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ trixie, testing, sid ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          file: docker/builder.dockerfile
          push: true
          tags: turnertech/nmbs-builder:${{ matrix.release }}
          build-args: |
            DEBIAN_RELEASE=${{ matrix.release }}
