name: Build nmbs

on:
  push:
    paths:
      - '.github/workflows/ci-nmbs.yml'
      - 'targets/**'
      - 'cmake/**'

jobs:
  build-nmbs:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v7
        with:
          file: docker/build.dockerfile
          push: false
          tags: turnertech/nmbs:latest
          build-args: |
            DEBIAN_RELEASE=trixie
