name: Build nmbs

on:
  push:
    paths:
      - 'targets/**'
      - 'cmake/**'
      - '.github/workflows/ci-nmbs.yml'

jobs:
  build-nmbs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ trixie, testing, sid ]
    container:
      image: turnertech/nmbs-builder:${{ matrix.release }}
      options: --user nmbs
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
